version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - '/'
    schedule:
      interval: weekly
    target-branch: develop

  - package-ecosystem: npm
    directories:
      - '/'
    schedule:
      interval: daily
    target-branch: develop
