import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        ...defaultTheme.colors,
        primary: {
          DEFAULT: "var(--color-primary-500)",
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary-500)",
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
        },
        helper: {
          green: "var(--color-helper-green)",
          yellow: "var(--color-helper-yellow)",
          red: "var(--color-helper-red)",
          blue: "var(--color-helper-blue)",
          icon: "var(--color-helper-icon)",
          outline: "var(--color-helper-outline)",
        },
        text: {
          high: "var(--color-text-high)",
          medium: "var(--color-text-medium)",
          low: "var(--color-text-low)",
        },
        icon: {
          high: "var(--color-icon-high)",
          medium: "var(--color-icon-medium)",
          low: "var(--color-icon-low)",
        },
        elevation: {
          surface: "var(--color-elevation-surface)",
          "01dp": "var(--color-elevation-01dp)",
          "02dp": "var(--color-elevation-02dp)",
          "03dp": "var(--color-elevation-03dp)",
          "04dp": "var(--color-elevation-04dp)",
          "05dp": "var(--color-elevation-05dp)",
        },
      },
      opacity: {
        semiopaque: "var(--opacity-semiopaque)",
        intense: "var(--opacity-intense)",
        medium: "var(--opacity-medium)",
        light: "var(--opacity-light)",
        semitransparent: "var(--opacity-semitransparent)",
      },
      borderRadius: {
        none: "var(--border-radius-none)",
        xs: "var(--border-radius-xs)",
        sm: "var(--border-radius-sm)",
        md: "var(--border-radius-md)",
        lg: "var(--border-radius-lg)",
        pill: "var(--border-radius-pill)",
      },
      borderWidth: {
        none: "var(--border-width-none)",
        hairline: "var(--border-width-hairline)",
        thin: "var(--border-width-thin)",
        thick: "var(--border-width-thick)",
        heavy: "var(--border-width-heavy)",
      },
      boxShadow: {
        level: {
          1: "var(--drop-shadow-level-1)",
          2: "var(--drop-shadow-level-2)",
          3: "var(--drop-shadow-level-3)",
          4: "var(--drop-shadow-level-4)",
        },
      },
      spacing: {
        nano: "var(--spacing-nano)",
        xxxxs: "var(--spacing-xxxxs)",
        xxxs: "var(--spacing-xxxs)",
        xxs: "var(--spacing-xxs)",
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        xxl: "var(--spacing-xxl)",
        xxxl: "var(--spacing-xxxl)",
        xxxx: "var(--spacing-xxxxl)",
        huge: "var(--spacing-huge)",
        giant: "var(--spacing-giant)",
        extraGiant: "var(--spacing-extra-giant)",
      },
      fontFamily: {
        primary: "var(--font-family-primary)",
        secondary: "var(--font-family-secondary)",
      },
      fontSize: {
        xxxs: "var(--font-size-xxxs)",
        xxs: "var(--font-size-xxs)",
        xs: "var(--font-size-xs)",
        sm: "var(--font-size-sm)",
        md: "var(--font-size-md)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        xxl: "var(--font-size-xxl)",
        xxxl: "var(--font-size-xxxl)",
        xxxx: "var(--font-size-xxxxl)",
        display: "var(--font-size-display)",
        giant: "var(--font-size-giant)",
      },
      fontWeight: {
        regular: "var(--font-weight-regular)",
        medium: "var(--font-weight-medium)",
        semibold: "var(--font-weight-semibold)",
        bold: "var(--font-weight-bold)",
      },
      lineHeight: {
        default: "var(--line-height-default)",
        xs: "var(--line-height-xs)",
      },
    },
  },
  plugins: [],
};
